name: CI/CD Workflow

on:
 

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/react-app:latest

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group leakplanting_group --name leakplanting --overwrite-existing

      - name: Create Namespace if not exists
        run: |
          kubectl get namespace leakplanting || kubectl create namespace leakplanting

      - name: Deploy to AKS
        uses: azure/k8s-deploy@v1
        with:
          manifests: |
            kubernetes/deployment.yml
            kubernetes/service.yml
          images: |
            ${{ secrets.ACR_LOGIN_SERVER }}/react-app:latest
          namespace: leakplanting
          strategy: recreate

      - name: Deploy Uptime Kuma
        run: |
          kubectl get namespace uptime-kuma || kubectl create namespace uptime-kuma
          kubectl apply -f kubernetes/uptime-kuma.yaml
