name: Check kubernetes files

on:
 

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Lint k8s manifest files
        uses: azure/k8s-lint@v3
        with:
          manifests: |
            kubernetes/deployment.yml
            kubernetes/service.yml
          kubeconformOpts: -ignore-missing-schemas
          lintType: kubeconform
          namespace: default
